### ISSUE TITLE
using IfcOpenShell_Python "georeference-ifc"

### ISSUE THREAD

**Issue by Takieddinex** [stijngoedertier/georeference-ifc#2]
Hello ! 
I have cloned the IfcOpenShell folder with all the dependencies only to have the ifcopenshell and ifcopenshell.geom libraries and OCC.Display.WebGl.jupyter_render so I am wondering what to do to get it to work please. 

![image](https://user-images.githubusercontent.com/95845810/162911806-0504194c-54ab-45d4-b680-aa6e62bc530c.png)
![image](https://user-images.githubusercontent.com/95845810/162911922-84ac10d0-68f8-4604-8619-5529ba24d25f.png)
![image](https://user-images.githubusercontent.com/95845810/162911989-fb4e5091-7b79-4e14-aba4-10d9237bacb2.png)

**Comment by stijngoedertier** [comment]
@Takieddinex , appologies for my late reply. Perhaps this may still be relevant.

This is intended to run via mybinder.org. See the link in the README.md folder:

https://mybinder.org/v2/gh/stijngoedertier/georeference-ifc/master?labpath=how-to-georeference-ifc-file.ipynb 

If you want to try this on your machine, you will need to install Python with [Conda](https://docs.conda.io). You can then create an environment using the provided `environment.yml` file. 

```bash
conda env create -f environment.yml
conda env list
conda activate ifcopenshell
```

Also, have a look at the [IfcOpenShell](https://github.com/IfcOpenShell/IfcOpenShell#installing-ifcopenshell-with-conda) project.
